<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-8">
        <h1>Crear producto</h1>
    </div>
</div>

<?php echo $this->getContent(); ?>

<?php if (isset($messagesError) && !empty($messagesError)) { ?>
    <div class="alert alert-warning">
        <?php foreach ($messagesError as $mensage) { ?>
            <?php echo $mensage; ?>
        <?php } ?>
    </div>
<?php } ?>

<?php
    echo $this->tag->form(
        [
            "/admin/productos/crear",
            "autocomplete" => "off",
            "class" => "form-row",
            "method" => "post",
            "enctype" => "multipart/form-data"
        ]
    );
?>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldNombre">Nombre</label>
        <?php echo $this->tag->textField(["nombre_producto", "class" => "form-control", "id" => "fieldNombre"]) ?>
    </div>
</div>

<div class="col-md-6 col-sm-6 col-xs-6">
    <div class="form-group">
        <label for="fieldPrecio">Precio</label>
        <?php echo $this->tag->textField(["precio", "class" => "form-control", "id" => "fieldPrecio"]) ?>
    </div>
</div>

<div class="col-md-6 col-sm-6 col-xs-6">
    <div class="form-group">
        <label for="fieldEnlace">Enlace</label>
        <?php echo $this->tag->textField(["enlace", "class" => "form-control", "id" => "fieldEnlace"]) ?>
    </div>
</div>

<div class="form-group col-md-12 col-sm-12 col-xs-12">
    <label for="fieldNombre">Categoria</label>
    <?php
        echo $this->tag->select(
        [
            'categoria_id',
            $categorias,
            'using' => [
                'id',
                'nombre',
            ],
            'useEmpty' => true,
            'emptyText'  => 'Elige una categoría',
            'class' => 'form-control'
        ]);
    ?>
</div>


<div class="form-group col-md-12 col-sm-12 col-xs-12">
    <label for="fieldImagen">Imagen</label>
    <?php echo $this->tag->fileField(["imagen", "class" => "form-control", "id" => "fieldImagen"]) ?>
</div>

<div class="col-md-12 col-sm-12 col-xs-12 textcenter">
    <?php echo $this->tag->submitButton(["Crear", "class" => "btn btn-default"]) ?>
</div>

<?php echo $this->tag->endForm(); ?>