<div class="row">
    <h1>Listado de productos</h1>
</div>


<div class="box">
    <?php
        echo $this->tag->form(
            [
                "/admin/productos",
                "autocomplete" => "off",
                "class" => "form-row"
            ]
        );
    ?>
    <div class="form-group col-md-4 col-sm-4 col-xs-12">
        <label for="fieldNombre">Categoria</label>
        <?php
            echo $this->tag->select(
            [
                'categoria_id',
                $categorias,
                'using' => [
                    'id',
                    'nombre',
                ],
                'useEmpty' => true,
                'emptyText'  => 'Elige una categoría',
                'class' => 'form-control'
            ]);
        ?>
    </div>
    <div class=" col-md-12 col-sm-12 col-xs-12 textcenter">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]); ?>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<table class="table margintop4">
    <thead>
        <tr>
            <th>Producto</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($page->items)) { ?>
            <?php foreach ($page->items as $producto): ?>
                <tr>
                    <td><?php echo $producto->nombre_producto; ?></td>
                    <td><?php echo $this->tag->linkTo(["/admin/productos/editar/" . $producto->id, "Editar"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["/admin/productos/delete/" . $producto->id, "Borrar", 'onClick' => 'return confirm("¿estás seguro?");']); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php } ?>
    </tbody>
</table>

<div class="paginacion">
    <p><?php echo $page->current, "/", $page->total_pages ?></p>
    <ul>
        <li><?php echo $this->tag->linkTo("/admin/productos/index", "Primero") ?></li>
        <li><?php echo $this->tag->linkTo("/admin/productos/index?page=" . $page->before, "Anterior") ?></li>
        <li><?php echo $this->tag->linkTo("/admin/productos/index?page=" . $page->next, "Siguiente") ?></li>
        <li><?php echo $this->tag->linkTo("/admin/productos/index?page=" . $page->last, "Último") ?></li>
     </ul>
</div>