<div class="bgproductos">
    <div class="container">
        <div style="background: #f7f5f5; padding: 15px; border-top:2px solid #99bf10; border-bottom:2px solid #99bf10;" class="texto-descripcion"><p><?php echo $textoInicio; ?></p></div>
        </br>
        <?php foreach ($categoriasPrincipales as $categoriaPrincipal) { ?>
            <a href="/<?php echo $categoriaPrincipal->slug; ?>">
                <div class="bloque-producto">
                    <p class="nombre"><?php echo $categoriaPrincipal->nombre; ?></p>
                    <br>
                    <amp-img src="<?php echo $categoriaPrincipal->imagen; ?>" width="250" height="150" layout="intrinsic" alt="<?php echo $categoriaPrincipal->nombre; ?>" title="<?php echo $categoriaPrincipal->nombre; ?>"></amp-img>
                    <p class="descripcion"><?php echo $this->Truncate->truncar(strip_tags($categoriaPrincipal->description_seo), 75); ?></p>
                    <br>
                </div>
            </a>
        <?php } ?>
        <div class="clearfix"></div>
        <!-- ovnis reales 2 -->
        <amp-ad width="100vw" height="320"
            type="adsense"
            data-ad-client="ca-pub-9579326870526141"
            data-ad-slot="9450213218"
            data-auto-format="rspv"
            data-full-width="">
        <div overflow=""></div>
        </amp-ad>
        </br>
        <div style="background: #f7f5f5; padding: 15px; border-top:2px solid #99bf10; border-bottom:2px solid #99bf10;" class="texto-descripcion">
            <?php if (DOMINIO_SELECT == 'es') { ?>
                <h2>Ovnis Reales, tu tienda online de productos de ufología y extraterrestres</h2>
                <p>
                    Los ufos siempre han sido un tema en boca de todos, se han visto muchos ovnis en el cielo y en la mayoría de las veces nos hemos quedado
                    con la duda de si procedía de La Tierra o de una galaxia muy lejana.
                </p>
                <p>
                    Esta tienda online te ofrece una selección de artículos de otro mundo elegidos especialmente para ti, son los más baratos del mercado, 
                    lo único que debes tener para comprarlos es mucha personalidad, ya que no todo el mundo puede ser original para llevar este merchandising.
                    Date prisa, las existencias se puede acabar y te podrías quedar sin tus productos.
                </p>
                <h2>Los mejores casos de ovnis del <?php echo date('Y'); ?></h2>
                <p>
                    Este año el Pentágono hizo públicas unas grabaciones del gobierno de los EEUU sobre Objetos Voladores No Identificados. Esto hace que cada vez 
                    más científicos respetados defiendan la búsqueda extraterrestre en otro planetas e inclusive en el nuestro debido a todos los fenómenos que 
                    nos rodean y que no tienen explicación.
                </p>
                <p></p>
            <?php } else { ?>
                <h2>Tienda online especializada en Ovnis Reales y Extraterrestres</h2>
                <p>
                    Los ovnis siempre han sido un tema altamente controvertido, se han visto muchos ovnis en el cielo y en la mayoría de las veces nos hemos quedado
                    con la duda de si procedía de La Tierra o de un planeta muy lejano.
                </p>
                <p>
                    La tienda onlien de Ovnis Reales te ofrece una selección de productos de otro mundo elegidos especialmente para ti, son los más baratos del mercado, 
                    lo único que debes tener para comprarlos es mucha personalidad, ya que no mucha gente puede ser original para llevar este merchandising.
                    No olvides que las existencias no son ilimitadas.
                </p>
                <h2>Los mejores ovnis y extraterrestres, año <?php echo date('Y'); ?></h2>
                <p>
                    Este año el gobierno de los EEUU hizo públicos unos videos sobre ovnis que tenía el Pentagono guardados. Esto hace que cada vez 
                    más científicos respetados alrededor de todo el mundo defiendan la búsqueda de vida extraterrestre en otros planetas e inclusive 
                    en el nuestro debido a todos los casos de ovnis y extraterrestres que nos rodean.
                </p>
            <?php } ?>
        </div>
    </div>
</div>