<div class="row">
    <h1>Listado de video facebook</h1>
</div>
<table class="table margintop4">
    <thead>
        <tr>
            <th>Título</th>
            <th>Creado</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($page->items)) { ?>
            <?php foreach ($page->items as $video): ?>
                <tr>
                    <td><?php echo $video->titulo; ?></td>
                    <td><?php echo date('d-m-Y', strtotime($video->created)); ?></td>
                    <td><?php echo $this->tag->linkTo(["admin/videosfacebook/editar/" . $video->id, "Editar"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["admin/videosfacebook/delete/" . $video->id, "Borrar", 'onClick' => 'return confirm("¿estás seguro?.");']); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php } ?>
    </tbody>
</table>

<div class="paginacion">
    <p><?php echo $page->current, "/", $page->total_pages ?></p>
    <ul>
        <li><?php echo $this->tag->linkTo("admin/videosfacebook/index", "Primero") ?></li>
        <li><?php echo $this->tag->linkTo("admin/videosfacebook/index?page=" . $page->before, "Anterior") ?></li>
        <li><?php echo $this->tag->linkTo("admin/videosfacebook/index?page=" . $page->next, "Siguiente") ?></li>
        <li><?php echo $this->tag->linkTo("admin/videosfacebook/index?page=" . $page->last, "Último") ?></li>
     </ul>
</div>