<footer>
    <div class="container">
        <ul>
            <?php foreach ($categoriasPrincipalesFooter as $enlace) { ?>
                <li><a title="<?php echo $enlace->texto_enlace_footer; ?>" alt="<?php echo $enlace->texto_enlace_footer; ?>" href="<?php echo $enlace->slug; ?>"><?php echo $enlace->texto_enlace_footer; ?></a></li>
            <?php } ?>
            <li>© Ovnis Reales <?php echo date('Y'); ?>. Todos los derechos reservados.</li>
        </ul>
    </div>
</footer>