<header>
    <div class="container">
        <a href="/" class="logo"><img src="/img/common/logo-ovnis-reales.svg" alt="Ovnis Reales. Comercio online productos ovnis y extraterrestres" /></a>
    </div>
</header>
<!--<div class="container">
    <div class="publi">
        <span>Publicidad</span>
    </div>
</div>-->
<div class="titular">
    <h1><?php echo $h1; ?></h1>
    <div class="select">
        <?php
            echo $this->tag->select(
            [
                'selectLanguage',
                $languages,
                'using' => [
                    'language',
                    'name',
                ],
                'emptyText'  => 'Elige tu país',
            ]);
        ?>
    </div>
</div>