<div class="bgproductos">
    <div class="container">
        <?php foreach ($categoriasPrincipales as $categoriaPrincipal) { ?>
            <a href="/<?php echo $categoriaPrincipal->slug; ?>">
                <div class="bloque-producto">
                    <p class="nombre"><?php echo $categoriaPrincipal->nombre; ?></p>
                    <br>
                    <?php
                        echo $this->tag->image(
                            [
                                $categoriaPrincipal->imagen,
                                'alt' => $categoriaPrincipal->nombre,
                                'title' => $categoriaPrincipal->nombre/*,
                                'class' => 'img-responsive'*/
                                ]
                            );
                    ?>
                    <p class="descripcion"><?php echo $this->Truncate->truncar(strip_tags($categoriaPrincipal->description_seo), 75); ?></p>
                    <br>
                </div>
            </a>
        <?php } ?>
        <div class="clearfix"></div>
    </div>
</div>