<div class="bgproductos">
    <div class="container">
        <ol class="breadcrumbs">
            <?php $this->Breadcrumbs->output(); ?>
        </ol>
        <?php echo $this->view->partial('partials/nav'); ?>
        <p><?php echo $categoria->descripcion_principal; ?></p>
        <?php foreach ($productos as $producto) { ?>
            <div class="bloque-producto">
                <a target="_blank" onclick="estadisticaProducto(<?php echo $producto->id; ?>)" href="<?php echo $producto->enlace; ?>">
                    <?php 
                        echo $this->tag->image(
                            [
                                $producto->imagen,
                                'alt' => $producto->nombre_producto,
                                'title' => $producto->nombre_producto,
                                'class' => 'img-responsive'
                                ]
                            );
                    ?>
                </a>
                <br>
                <p class="descripcion"><?php echo $this->Truncate->truncar(strip_tags($producto->nombre_producto), 75); ?></p>
                <?php $oferta = ($producto->es_rebajado == 1) ? "Oferta " : ""; ?>
                <?php if ($producto->TipoMonedas->id == 1) { ?>
                    <span class="descuento"><?php echo $oferta . $producto->precio; ?>&nbsp;<?php echo $producto->TipoMonedas->tipo; ?></span>
                <?php } else { ?>
                    <span class="descuento"><?php echo $oferta . $producto->TipoMonedas->tipo; ?>&nbsp;<?php echo $producto->precio; ?></span>
                <?php } ?>
                <br>
                <a target="_blank" onclick="estadisticaProducto(<?php echo $producto->id; ?>)" href="<?php echo $producto->enlace; ?>" class="button">Comprar</a>
            </div>
        <?php } ?>
        <div class="clearfix"></div>
        <p><?php echo $categoria->descripcion_secundaria; ?></p>
        <?php if (isset($contenidoRelacionado)) { ?>
            <h2>También te puede interesar</h2>
        <?php } ?>
    </div>
</div>