<!-- Breadcrumbs -->
<ol class="breadcrumbs">
    <?php $this->Breadcrumbs->output(); ?>
</ol>
<div class="col-sm-12 aligner aligner--centerHoritzontal aligner--centerVertical">
    <h1><?php echo $categoria->nombre; ?></h1>
</div>
<div class="row">
    <?php foreach ($productos as $producto) { ?>
        <div class="col-sm-4 aligner aligner--centerHoritzontal aligner--centerVertical">
            <div class="container">
                <a class="producto-amazon" onclick="estadisticaProducto(<?php echo $producto->id; ?>)" target="_blank" href="<?php echo $producto->enlace; ?>">
                    <div class="col-sm-12 aligner aligner--centerHoritzontal aligner--centerVertical">
                        <?php echo $this->Truncate->truncar(strip_tags($producto->nombre_producto), 75); ?>
                    </div>
                    <div class="col-sm-12 aligner aligner--centerHoritzontal aligner--centerVertical">
                        <?php echo $this->tag->image(
                            [
                                $producto->imagen,
                                'alt' => $producto->nombre_producto,
                                'title' => $producto->nombre_producto
                                ]
                            );
                        ?>
                    </div>
                </a>
                <div class="container">
                    <div class="row">
                            <div class="col aligner aligner--contentEnd">
                                <?php if ($producto->es_rebajado == 1) { ?>
                                    <ul>
                                        <li class="tag">
                                            <a href="#">Rebajado</a>
                                        </li>
                                    </ul>
                                <?php } ?>
                            </div>
                            <div class="col aligner aligner--contentEnd">
                                <?php if ($producto->TipoMonedas->id == 1) { ?>
                                    <ul>
                                        <li class="badge"><?php echo $producto->precio; ?>&nbsp;<?php echo $producto->TipoMonedas->tipo; ?></li>
                                    </ul>
                                <?php } else { ?>
                                    <ul>
                                        <li class="badge"><?php echo $producto->TipoMonedas->tipo; ?>&nbsp;<?php echo $producto->precio; ?></li>
                                    </ul>
                                <?php } ?>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
