<div class="row">
	<div class="col-md-3 col-sm-3 col-3">
		<?php
			echo $this->tag->image(
			    [
			       '/img/common/logo-ovnis-reales.svg',
			       'alt' => 'Ovnis Reales Logo',
			       'class' => 'img-fluid'
			    ]
			);
		?>
	</div>
	<?php if (isset($usuarioAdmin) && !empty($usuarioAdmin)) { ?>
		<div class="col-md-3 col-sm-3 col-3">
			<span style="margin-right:20px"><?php echo 'Hola David'; ?></span>
			<a href="/admin/usuarios/logoutAdmin" class="">Desconectar</a>
		</div>
		<div class="col-md-3 col-sm-3 col-3">
			<div class="select">
				<?php
					echo $this->tag->select(
					[
						'selectLanguage',
						$languages,
						'using' => [
							'language',
							'name',
						],
						'emptyText'  => 'Elige tu país',
					]);
				?>
			</div>
		</div>
	<?php } ?>
</div>

