<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-8">
        <h1>Crear categoria</h1>
    </div>
</div>

<?php echo $this->getContent(); ?>

<?php if (isset($messagesError) && !empty($messagesError)) { ?>
    <div class="alert alert-warning">
        <?php foreach ($messagesError as $mensage) { ?>
            <?php echo $mensage; ?>
        <?php } ?>
    </div>
<?php } ?>

<?php
    echo $this->tag->form(
        [
            "/admin/categorias/crear",
            "autocomplete" => "off",
            "class" => "form-row",
            "method" => "post",
            "enctype" => "multipart/form-data"
        ]
    );
?>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldNombre">Nombre</label>
        <?php echo $this->tag->textField(["nombre", "class" => "form-control", "id" => "fieldNombre"]) ?>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldDescripcionPrincipal">Descripción Principal</label>
        <?php echo $this->tag->textArea(["descripcion_principal", "class" => "form-control", "id" => "descripcion_principal", "name" => "descripcion_principal"]) ?>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldDescripcionSecundaria">Descripción Secundaria</label>
        <?php echo $this->tag->textArea(["descripcion_secundaria", "class" => "form-control", "id" => "descripcion_secundaria", "name" => "descripcion_secundaria"]) ?>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldTitleSeo">Título SEO</label>
        <?php echo $this->tag->textField(["title_seo", "class" => "form-control", "id" => "fieldTitleSeo"]) ?>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldDescriptionSeo">Descripción SEO</label>
        <?php echo $this->tag->textField(["description_seo", "class" => "form-control", "id" => "fieldDescriptionSeo"]) ?>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="form-group">
        <label for="fieldKeywords">Keywords Ejemplo: camiseta ovnis,tazas extraterrestres</label>
        <?php echo $this->tag->textField(["keywords", "class" => "form-control", "id" => "fieldKeywords"]) ?>
    </div>
</div>

<div class="form-group col-md-6 col-sm-6 col-xs-12">
    <label for="fieldImagen">Imagen</label>
    <?php echo $this->tag->fileField(["imagen", "class" => "form-control", "id" => "fieldImagen"]) ?>
</div>

<div class="col-md-12 col-sm-12 col-xs-12 textcenter">
    <?php echo $this->tag->submitButton(["Crear", "class" => "btn btn-default"]) ?>
</div>

<?php echo $this->tag->endForm(); ?>