<header>
    <div class="container">
        <a href="/" class="logo">
            <amp-img src="/img/common/logo-ovnis-reales.svg" width="130" height="30" layout="responsive" alt="Ovnis Reales. Comercio online productos ovnis y extraterrestres" title="Ovnis Reales. Comercio online productos ovnis y extraterrestres"></amp-img>
        </a>
    </div>
</header>
<div class="container">
    <div class="publi">
        <!-- ovnis reales 1 -->
        <amp-ad width="100vw" height="320"
            type="adsense"
            data-ad-client="ca-pub-9579326870526141"
            data-ad-slot="8174103642"
            data-auto-format="rspv"
            data-full-width="">
        <div overflow=""></div>
        </amp-ad>
    </div>
</div>

<div class="titular">
    <h1><?php echo $h1; ?></h1>
    <div class="select">
        <select id="selectLanguage" name="selectLanguage">
            <?php foreach ($languages as $key => $language) { ?>
                <option value="<?php echo $key; ?>"><?php echo $language; ?></option>
            <?php } ?>
        </select>
    </div>
</div>