<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $titleSeo; ?></title>
        <meta name="description" content="<?php echo $descriptionSeo; ?>">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <?php $this->assets->outputCss('localCss'); ?>
    </head>
    <body>
        <div class="container-medium">
            <?php echo $this->view->partial('partials/header'); ?>
            <?php echo $this->getContent(); ?>
        </div>
    </body>
    <?php $this->assets->outputJs(); ?>
</html>
